pub mod app_state;
pub mod audit_log;
pub mod auto_backup;
pub mod backup_workspace;
pub mod central_repo;
pub mod cli_bridge;
pub mod content_hash;
mod credential_cache;
mod credential_file;
pub mod crypto;
pub mod error;
pub mod file_watcher;
mod gh_credentials;
pub mod git2_engine;
pub(crate) mod git_auth_source;
pub mod git_backup;
pub mod git_credentials;
pub(crate) mod git_failure;
pub mod git_fetcher;
pub mod github_api;
pub mod install_cancel;
pub mod installer;
pub mod log_sanitize;
pub mod merge;
pub mod migrations;
pub mod panic_log;
pub mod path_guard;
pub mod project_scanner;
pub mod removals;
pub mod repo_lock;
pub mod scanner;
pub mod scenario_service;
mod shared_library;
pub(crate) mod shared_skill_index;
pub mod skill_auto_updater;
pub mod skill_metadata;
pub mod skill_store;
pub mod skillssh_api;
pub mod sync_engine;
pub mod sync_metadata;
pub mod timing;
pub mod tool_adapters;
mod tool_detection;
pub mod tool_service;
